var ofLinks = {
  "instagram_kawaii": "https://onlyfans.com/aleksavicee",
  "instagram_aleksa": "https://onlyfans.com/aleksavicee",
  "twitter": "https://onlyfans.com/aleksavicee",
  "reddit": "https://onlyfans.com/aleksavicee",
  "default": "https://onlyfans.com/aleksavicee"
};

// Auto-generated by Aleksa Admin Panel
// Do not edit manually
