var ofLinks = {
  "instagram_kawaii": "https://onlyfans.com/aleksavicee",
  "instagram_aleksa": "https://onlyfans.com/aleksavicee",
  "twitter": "https://onlyfans.com/aleksavicee",
  "reddit": "https://onlyfans.com/aleksavicee",
  "default": "https://onlyfans.com/aleksavicee",
  "fansly": "https://fansly.com/kawaii_hater/posts",
  "telegram": "https://t.me/+-ZQrm7cIqpowMWZi",
  "twitter_url": "https://x.com/"
};

// Auto-generated by Aleksa Admin Panel
// Do not edit manually
